# 1. Dirección de la base de datos (URL)
# El puerto por defecto es 5432 y el nombre debe ser el que creaste en pgAdmin
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

# 2. Tus credenciales de acceso
#spring.datasource.username=postgres
#spring.datasource.password=admin

# 3. Configuración de JPA / Hibernate
# 'update' hará que Spring cree o actualice las tablas automáticamente según tus clases de Java
#spring.jpa.hibernate.ddl-auto=update
# Esto mostrará en la consola de VS Code las consultas SQL que Spring está haciendo por debajo
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 
# ==========================================
# CONEXIÓN A NEON (POSTGRESQL EN LA NUBE)
# ==========================================

# 1. La URL (Nota cómo le agregamos "jdbc:" al principio)
spring.datasource.url=jdbc:postgresql://ep-fancy-sky-an7qc1se-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

# 2. Tu Usuario
spring.datasource.username=neondb_owner

# 3. Tu Contraseña
spring.datasource.password=npg_lTNH63KWxwDS

# 4. El driver para que Java sepa hablar con Postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 5. ¡VITAL PARA LA PRIMERA VEZ! Crea las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# ==========================================
# AJUSTES DE HIKARI PARA BASES DE DATOS SERVERLESS (NEON)
# ==========================================

# 1. Vida máxima de la conexión (5 minutos = 300000 ms)
# Le dice a Java que mate sus propias conexiones antes de que Neon lo haga a la fuerza.
spring.datasource.hikari.max-lifetime=300000

# 2. Tiempo para mantener viva la conexión (45 segundos)
# Envía un "latido" silencioso a Neon para decirle "¡Sigo aquí, no me cortes!"
spring.datasource.hikari.keepalive-time=45000

# 3. Tiempo de espera de conexión (30 segundos)
# Le da más tiempo a Java para conectar por si Neon estaba "dormido" y tarda en despertar.
spring.datasource.hikari.connection-timeout=30000